services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: booking_ota
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - my_postgres14_data:/var/lib/postgresql/data
    # Giữ lại healthcheck cho Postgres vì image này hỗ trợ sẵn
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d booking_ota"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - npm_network

  redis:
    image: redis:7-alpine
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - npm_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - npm_network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_started
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - npm_network

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    networks:
      - npm_network

  spring-app:
    build: ./Accomodation-Booking-OTA
    container_name: spring-app
    env_file: ./Accomodation-Booking-OTA/.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_started
    restart: on-failure
    networks:
      - npm_network

  booking-ui:
    build:
      context: .
      dockerfile: booking-ui/Dockerfile
    container_name: booking-ui
    restart: always
    networks:
      - npm_network
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    networks:
      - npm_network
    ports:
      - "9000:9000"    # API Port
      - "9001:9001"    # Web Console Port
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123 # Change this for production!
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

networks:
  npm_network:
    external: true
    name: tools-server_proxy

volumes:
  my_postgres14_data:
    external: true
  minio_data:
